name: API Automation CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Start FastAPI server
      run: uvicorn app:app --host 0.0.0.0 --port 8000 &

    - name: Wait for API to be ready
      run: |
        echo "Waiting for API to start..."
        sleep 10

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build and test
      run: mvn clean test

    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: target/allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.6
      with:
        allure_results: target/allure-results
        allure_report: target/allure-report
        keep_reports: true

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-report
