name: API Automation CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.2

    - name: Set up JDK 11
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3.3.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Install dependencies and run tests
      run: mvn clean test

    - name: Upload Allure Results
      uses: actions/upload-artifact@v3.1.2
      with:
        name: allure-results
        path: target/allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.6
      with:
        allure_results: target/allure-results
        allure_report: target/allure-report
        keep_reports: true

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-report
