name: Minimal CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Start FastAPI server
      run: uvicorn app:app --host 0.0.0.0 --port 8000 &
    
    - name: Wait for API to be ready
      run: |
        echo "Waiting for API to start..."
        sleep 10

    - name: Build and test
      run: mvn clean test
